stages:
- build
- library

build_cpp:
  image: ubuntu:20.04
  stage: build
  before_script:
  - apt-get update
  - apt-get install software-properties-common -y
  - add-apt-repository ppa:mhier/libboost-latest -y
  - apt-get install build-essential gcc-10 g++-10 libboost1.74-dev -y
  script:
  - cd test
  - make
  tags:
  - docker

build_python:
  image: ubuntu:20.04
  stage: library
  before_script:
  - apt-get update
  - apt-get install build-essential gcc-10 g++-10 python3 python3-dev python3-venv -y
  script:
  - cd python && python3 -m venv .venv && source .venv/bin/activate && pip install -r requirements-ci.txt
  - CC=gcc-10 CXX=g++-10 python setup.py bdist_wheel
  dependencies:
  - build_cpp
  artifacts:
    paths:
      - python/dist/
  tags:
  - docker
